#!/bin/bash

usage ()
{
    echo ""
    echo 'Usage : bible <book> <chapter>:<versicle>'
    echo ""
    exit
}

if [ "$1" = "" ]; then
    usage
fi

l=$1
c=$2
v=$3

d="$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
b=$d/rv60
export f=$d/format.rv60

if [ $# = 1 ]; then
    cat $b | grep ^$l | $f
elif [ $# = 2 ]; then
    cat $b | grep ^$l | grep -E ":[0]{0,2}$c:[0-9]{3}" | $f
else
    cat $b | grep ^$l | grep -E ":[0]{0,2}$c:[0-9]{3}" | grep -E "[0-9]{3}:[0]*$v:" | $f
fi
