#!/bin/bash

usage ()
{
    echo ""
    echo 'Usage : bible <book> <chapter>:<versicle>'
    echo ""
    exit
}

if [ "$1" = "" ]; then
    usage
fi

l=$1
c=$2
v=$3

b=$HOME/Documentos/Dropbox/git/Code/bible/rv60
export format=$HOME/Documentos/Dropbox/git/Code/bible/format.rv60

if [ $# = 1 ]; then
    cat $b | grep ^$l | $format
elif [ $# = 2 ]; then
    cat $b | grep ^$l | grep -E ":[0]{0,2}"$c":[0-9]{3}" | $format
else
    cat $b | grep ^$l | grep -E ":[0]{0,2}"$c":[0-9]{3}" | grep -E "[0-9]{3}:[0]*$v:" | $format
fi
